services:
  - type: web
    name: flaskbin
    env: python
    buildCommand: |
      pip install -r requirements.txt
      echo "Running PostgreSQL driver and database diagnostics..."
      python diagnose_psycopg2.py 
      echo "Diagnostics complete, continuing with build..."
    startCommand: gunicorn --bind 0.0.0.0:$PORT deploy_wsgi:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: SESSION_SECRET
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: flaskbin_db
          property: connectionString
      - key: FLASK_ENV
        value: production
      - key: SQLALCHEMY_SILENCE_UBER_WARNING
        value: "1"
      - key: SQLALCHEMY_WARN_20
        value: "0"

databases:
  - name: flaskbin_db
    plan: free
    databaseName: flaskbin
    user: flaskbin_user