services:
  - type: web
    name: flaskbin
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --bind 0.0.0.0:$PORT deploy_wsgi:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: SESSION_SECRET
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: flaskbin_db
          property: connectionString

databases:
  - name: flaskbin_db
    plan: free
    databaseName: flaskbin
    user: flaskbin_user