services:
  - type: web
    name: flaskbin
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --bind 0.0.0.0:$PORT minimal_wsgi:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0